### ISSUE TITLE
Convert ETL to service

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#30]
### Motivation
With multiple applications in Avni now, we need to start delineating the boundary of data for each service. This becomes important for us to make sense of the data and actors working on the data. 

### Proposed End-State
https://docs.google.com/document/d/11RMG3JmfjUWicF11H1J7jt8JuMRi2Ib-R5NawkxlIbU/edit?usp=sharing

As a first step to get there, we will first move the ETL job into a service. 

### Tasks

- [x] - Upgrade to Java 17 and latest possible Spring/Boot versions
- [x] - Move to a Spring Boot service avni-etl
- [x] - Change CircleCI deploy for etl to target integration ec2 instance
- [x] - Add a ping service (https://int-staging.avniproject.org/etl/ping)
- [x] - Move the ETL job to run as a batch job (quartz/spring batch etc) every hour
- [x] - Setup systemd service for etl service
- [x] - Create CircleCI deploy for int-server and int-adminapp

**Comment by petmongrels** [comment]
Tasks - upgrade to the latest version of Java and Spring. Spike/discussion for pros and cons between spring batch and quartz.
Name - ETL seems a more accurate description.

**Comment by vinayvenu** [comment]
@petmongrels one of the discussion points we had was to extract observations (image urls) based on certain conditions (concept, program etc). If we need to have such apis within this service, ETL might not be the accurate.

**Comment by petmongrels** [comment]
I think this API ideally could be in OLTP provided we can improve the performance of the observations query. Temporarily we can have this in ETL as a hack but if the performance can be improved for obs then it can be moved to avni server. this is linked to our performance fixes.

**Comment by himeshr** [comment]
Code changes in avni-infra related to deploys.
CircleCI config changes in etl-service.
CircleCI config introduced for avni-int-service and avni-int-adminapp.
