### ISSUE TITLE
ETL enhancements v1

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#47]
This epic will make some necessary modifications that will improve operational and other capability of ETL. 

### Objectives
- Both implementers and users need to understand if the ETL for their organisation is healthy. Currently, the only way to find this out is by looking at the logs. In order to change that, we should be able to see status of ETL broken down by organisation.
- We also need to be able to run ETL for an organisation separately (with auth) so that any issues can be fixed separately without using up too much of system resources
- We also have to ensure that no two ETL job runs together to avoid issues of data corruption. 
- Lastly, there are some parts of ETL that have not migrated out to the schema level tables. Some stories will enable this

```[tasklist]
### Tasks
- [x] avniproject/avni-etl#49
- [x] avniproject/avni-etl#53
- [ ] avniproject/avni-etl#22
- [ ] avniproject/avni-etl#50
- [ ] avniproject/avni-etl#48
```
